name: DuinoMC-Core
version: '1.0-SNAPSHOT'
main: net.ramslayer.duinomccore.DuinoMCCore
api-version: '1.21'
softdepend: [ Vault ]
commands:
  duco:
    description: Manage servers economy
    usage: /duco <check/give/take> <player> [amount]
    aliases: [ eco ]
    permission: duino.command.economy.manage
  balance:
    description: Check your balance
    usage: /balance
    aliases: [ bal ]
    permission: duino.command.economy.bal
  pay:
    description: Pay another user
    usage: /pay <username> <amount>
    permission: duino.command.economy.pay
  deposit:
    description: Deposit DUCO to your minecraft profile
    usage: /deposit
    permission: duino.command.economy.deposit
  withdraw:
    description: Withdraw DUCO to your wallet
    usage: /withdraw <duino_username> <amount>
    permission: duino.command.economy.withdraw